### ISSUE TITLE
comments don't work inside the environment block

### ISSUE THREAD

**Issue by christopher-haueter** [etanzapinsky/mongoose#13]
@mnrubin @meirf

**Comment by mnrubin** [comment]
comments are a lexer thing, shouldn't be related to the grammar in any way.
keep in mind a comment goes from  the # till the end of the line.   Mind
sharing the code that's not working?

**Comment by christopher-haueter** [comment]
This works:

```
environment{
    int[2][2] x
    x[1][1] = 3
    print(x[1][1])
    # spurious comment
    action{
    }
    populate{       
    }
}

terminate{
}
analysis{
}
```

This does not:

```
environment{
    int[2][2] x
    x[1][1] = 3
    print(x[1][1])
    # spurious comment

    action{
    }
    populate{       
    }
}

terminate{
}
analysis{
}
```

**Comment by mnrubin** [comment]
it's possible that the issue is related to the newline/statement_list bug that Etan just caught and fixed. Try again when he pushes the bugfix. I doubt it's specific to the environment block, and prob has to do with the newline

**Comment by christopher-haueter** [comment]
Still breaks for me:

```
environment{
    int[2][3] x
    x[1][1] = 1
    print(x[1][1])
    x[1][2] = 2
    print(x[1][2])
    int y = x[1][1]
    print(y)
    # comment

    action{
    }
    populate{       
    }
}

terminate{
}
analysis{
}
```

Yields:

```
(plt)➜  mongoose git:(dev) ✗ ./manage.sh parser/main.py sample_code/list_declaration_and_access.mon
LexToken(NEWLINE,'\n',10,123)
Syntax error in input:
    Input: LexToken(NEWLINE,'\n',10,123)
Syntax error in input: program order must be: [agents] environment terminate analysis
result is of type <type 'NoneType'>
done
```

@meirf @mnrubin

**Comment by mnrubin** [comment]
what do you mean by "it breaks" ?  What type of error are you getting?

**Comment by christopher-haueter** [comment]
@mnrubin look again

**Comment by mnrubin** [comment]
ah, sorry, that last bit didn't show up in the github email.  I'll take a look tomorrow, at this point our errors are a bit general so it may be hard to tell what the problem is exactly, but it has something to do with the newlines I'd wager. Meir and I will fix it, thanks for finding the bug

**Comment by mnrubin** [comment]
This worked without problems (we just ran it). Are you still getting a bug @chrishaum ?

**Comment by christopher-haueter** [comment]
I haven't seen it again.
